### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.array([np.random.uniform(0, 1) for _ in range(10)])
vector_2 = np.random.rand(10)
vector, vector_2, vector.shape, vector_2.shape

(array([0.61225152, 0.20956925, 0.86396369, 0.32137429, 0.10401164,
        0.48300927, 0.51816828, 0.00936069, 0.09505471, 0.1419734 ]),
 array([0.39383552, 0.42774409, 0.90965034, 0.06590254, 0.4760063 ,
        0.44584453, 0.31250012, 0.44409447, 0.17843878, 0.84824616]),
 (10,),
 (10,))

In [3]:
matrix = np.array([[11, 14, 17],
             [20, 23, 26],
             [29, 32, 35]])
matrix, matrix.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [4]:
np.round(vector + 10, 2)

array([10.61, 10.21, 10.86, 10.32, 10.1 , 10.48, 10.52, 10.01, 10.1 ,
       10.14])

In [5]:
matrix * 2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [6]:
vector ** 2

array([3.74851919e-01, 4.39192703e-02, 7.46433265e-01, 1.03281432e-01,
       1.08184205e-02, 2.33297953e-01, 2.68498368e-01, 8.76225952e-05,
       9.03539841e-03, 2.01564468e-02])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [7]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [8]:
result_matrix = np.dot(B,A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

2. вектор розмірністю $2\mathtt{x}1$

In [9]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

3. Одержимо ту ж саму матрицю $2\mathtt{x}2,$ тієї ж розмірності як і матриця result_matrix

In [10]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [11]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [12]:
vector.T

array([0.61225152, 0.20956925, 0.86396369, 0.32137429, 0.10401164,
       0.48300927, 0.51816828, 0.00936069, 0.09505471, 0.1419734 ])

зміни не бачу

In [13]:
column_vector = np.expand_dims(vector, axis=1)
column_vector

array([[0.61225152],
       [0.20956925],
       [0.86396369],
       [0.32137429],
       [0.10401164],
       [0.48300927],
       [0.51816828],
       [0.00936069],
       [0.09505471],
       [0.1419734 ]])

In [14]:
vector

array([0.61225152, 0.20956925, 0.86396369, 0.32137429, 0.10401164,
       0.48300927, 0.51816828, 0.00936069, 0.09505471, 0.1419734 ])

column_vector $-$ це матриця розміром $10\texttt{x}1$ у якої єдиний вектор-стовпчик є транспонована версія вектор-рядка vector

In [15]:
column_vector.shape, vector.shape

((10, 1), (10,))

In [16]:
column_vector.T, column_vector.T.shape

(array([[0.61225152, 0.20956925, 0.86396369, 0.32137429, 0.10401164,
         0.48300927, 0.51816828, 0.00936069, 0.09505471, 0.1419734 ]]),
 (1, 10))